### ISSUE TITLE
An Issue with HTML Output

### ISSUE THREAD

**Issue by jspeed-meyers** [SourceCode-AI/aura#12]
**The bug**
When I run the Docker container and attempt to get HTML output, I get an error. The resulting HTML document says, "[31mNo such output format `html`[0m"

**To Reproduce**
Run this command:
```docker run -ti --rm sourcecodeai/aura:dev scan pypi://requests -f html > output.html```

**Expected behavior**
Expected a nicely formatted HTML document.

**Desktop (please complete the following information):**
 - OS: Catalina 10.15.7
 - Docker: Docker version 19.03.5, build 633a0ea

**Additional context**
I'm excited to use this feature. Nice work! Sorry if I'm doing something silly.

**Comment by RootLUG** [comment]
Can you confirm that you are running the latest dev docker image? If you have run the aura in docker before, that command would use the old image version which does not have HTML output format, you would need to run `docker pull sourcecodeai/aura:dev` to fetch the latest version first.  I'm just making sure the version you are using is the right one :)

The digest of the container that will be printed when you run docker pull should be `sha256:197b163219ecdc4103280526303d6b2ebea49ae1f2e6698ee2d8b41aa433096d` for the latest version that has the HTML output support

**Comment by jspeed-meyers** [comment]
@RootLUG, of course I'm doing something silly! I hadn't fetched the latest version. It's working now. Thank you! New problem though. Will open a new issue.
