### ISSUE TITLE
About AST Construction

### ISSUE THREAD

**Issue by KarthickRaja2002** [SourceCode-AI/aura#23]
@RootLUG ,

I need the following details about the Aura AST Parsing...

```
1. Can I get the information about how the AST tree is constructed in Aura?
2. What are classes used for constructing the AST? If possible, provide code flow.
3. Can I print the AST node or AST tree?
```

Thanks in Advance!

**Comment by RootLUG** [comment]
Aura is using a built-in python AST parser.
However there is a big difference between other projects doing the same thing, let me explain. Normally there is a limitation that when you install something or use the built-in AST parser under python3.9 for example you can't parse code from python3.10 if it uses the incompatible syntax, this is a common limitation in tools using the built-in AST parsing.
Aura is able to bypass that in a way that there is a special AST parser that is single file without any dependencies and can be injected into any python version. So when a code is analyzed, aura is trying to first find a python version that can parse the code (hence the need to configure `interpreters` in the config file), once a python interpreter is found that can parse the input code, it will inject the self-contained AST parser into it to extract the AST tree, serialize into JSON and that is send back to Aura
Aura then parses the JSON and reconstruct it back into the classes defined in `aura.analyzers.python.nodes` that are then further used in taint analysis, pattern matching etc...
The flow depends on the configuration as it can be fully customized but the default one is something like this:
- raw file analysis (no parsing, analyzes raw files like zip archives, binary files, extract packages/wheels etc..)
- code parsing (the AST parser injection and receiveing it as JSON in Aura)
- code conversion (Aura converts AST JSON into it's defined classes that are more suitable for further analysis)
- AST optimization (AST tree is transformed, optimized and enriched with information, for example constant folding etc..)
- taint flow analysis (once AST has all the information enriched and can't be further transformed it is passed through taint analysis to compute the taint flow)
- read only analysis (last stage, as name implies these stage does not change anything in AST tree and just uses the information provided by previous stage, this is for example pattern matching, SQL injection detection, malware detection etc.., all of these are read only operations that won't modify AST so they are also run in parallel, everything before this stage can and probably will modify parts of AST)

Aura has also a "parse_ast" that accepts a file, and outputs it's AST tree (either as text or as json), you can also specify which stages you want to run on the AST before it's printed so it also show modifications done to the AST tree, check the help on the command `aura parse_ast -h` for usage details
